# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20161010_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default=b'', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='pic_back',
            field=models.ImageField(null=True, upload_to=b'./shop/static/shop/itemspic'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pic_front',
            field=models.ImageField(null=True, upload_to=b'./shop/static/shop/itemspic'),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(to='shop.Size'),
        ),
    ]
