# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20161013_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Colours')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Item'),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Size'),
        ),
    ]
