# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20161014_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uniqueid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
