# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
