# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='colour',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Colours'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Size'),
        ),
    ]
