# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20161014_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(default=b'0', max_length=10),
        ),
    ]
